package org.companyLog.bean;


public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.id
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.log_id
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    private String logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.author_id
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    private String authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.create_time
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.reply_id
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    private String replyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.content
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.reply_content
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    private String replyContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.log_id
     *
     * @return the value of comment.log_id
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.log_id
     *
     * @param logId the value for comment.log_id
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    public void setLogId(String logId) {
        this.logId = logId == null ? null : logId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.author_id
     *
     * @return the value of comment.author_id
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    public String getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.author_id
     *
     * @param authorId the value for comment.author_id
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    public void setAuthorId(String authorId) {
        this.authorId = authorId == null ? null : authorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.create_time
     *
     * @return the value of comment.create_time
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.create_time
     *
     * @param createTime the value for comment.create_time
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.reply_id
     *
     * @return the value of comment.reply_id
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    public String getReplyId() {
        return replyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.reply_id
     *
     * @param replyId the value for comment.reply_id
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    public void setReplyId(String replyId) {
        this.replyId = replyId == null ? null : replyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.reply_content
     *
     * @return the value of comment.reply_content
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.reply_content
     *
     * @param replyContent the value for comment.reply_content
     *
     * @mbggenerated Wed Mar 15 12:40:08 CST 2017
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent == null ? null : replyContent.trim();
    }
}