package org.companyLog.bean;


public class Log {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.author_id
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    private String authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.is_limit_see
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    private Integer isLimitSee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.create_time
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.update_time
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.title
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.group_id
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    private Integer groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.read_num
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    private Integer readNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.summary
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.content
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.author_id
     *
     * @return the value of log.author_id
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public String getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.author_id
     *
     * @param authorId the value for log.author_id
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public void setAuthorId(String authorId) {
        this.authorId = authorId == null ? null : authorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.is_limit_see
     *
     * @return the value of log.is_limit_see
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public Integer getIsLimitSee() {
        return isLimitSee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.is_limit_see
     *
     * @param isLimitSee the value for log.is_limit_see
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public void setIsLimitSee(Integer isLimitSee) {
        this.isLimitSee = isLimitSee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.create_time
     *
     * @return the value of log.create_time
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.create_time
     *
     * @param createTime the value for log.create_time
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.update_time
     *
     * @return the value of log.update_time
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.update_time
     *
     * @param updateTime the value for log.update_time
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.title
     *
     * @return the value of log.title
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.title
     *
     * @param title the value for log.title
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.group_id
     *
     * @return the value of log.group_id
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.group_id
     *
     * @param groupId the value for log.group_id
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.read_num
     *
     * @return the value of log.read_num
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public Integer getReadNum() {
        return readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.read_num
     *
     * @param readNum the value for log.read_num
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public void setReadNum(Integer readNum) {
        this.readNum = readNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.summary
     *
     * @return the value of log.summary
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.summary
     *
     * @param summary the value for log.summary
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.content
     *
     * @return the value of log.content
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.content
     *
     * @param content the value for log.content
     *
     * @mbggenerated Tue Mar 14 23:47:47 CST 2017
     */
    public void setContent(String content) {
        this.content = content ;//== null ? null : content.trim();
    }
}