package org.companyLog.bean;

import java.util.Date;

public class LogCollection {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_collection.id
     *
     * @mbggenerated Sun Mar 19 00:34:47 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_collection.user_id
     *
     * @mbggenerated Sun Mar 19 00:34:47 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_collection.log_id
     *
     * @mbggenerated Sun Mar 19 00:34:47 CST 2017
     */
    private String logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_collection.create_time
     *
     * @mbggenerated Sun Mar 19 00:34:47 CST 2017
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_collection.id
     *
     * @return the value of log_collection.id
     *
     * @mbggenerated Sun Mar 19 00:34:47 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_collection.id
     *
     * @param id the value for log_collection.id
     *
     * @mbggenerated Sun Mar 19 00:34:47 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_collection.user_id
     *
     * @return the value of log_collection.user_id
     *
     * @mbggenerated Sun Mar 19 00:34:47 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_collection.user_id
     *
     * @param userId the value for log_collection.user_id
     *
     * @mbggenerated Sun Mar 19 00:34:47 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_collection.log_id
     *
     * @return the value of log_collection.log_id
     *
     * @mbggenerated Sun Mar 19 00:34:47 CST 2017
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_collection.log_id
     *
     * @param logId the value for log_collection.log_id
     *
     * @mbggenerated Sun Mar 19 00:34:47 CST 2017
     */
    public void setLogId(String logId) {
        this.logId = logId == null ? null : logId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_collection.create_time
     *
     * @return the value of log_collection.create_time
     *
     * @mbggenerated Sun Mar 19 00:34:47 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_collection.create_time
     *
     * @param createTime the value for log_collection.create_time
     *
     * @mbggenerated Sun Mar 19 00:34:47 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}