package org.companyLog.bean;

public class LogGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_group.id
     *
     * @mbggenerated Sat Mar 18 18:28:12 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_group.group_name
     *
     * @mbggenerated Sat Mar 18 18:28:12 CST 2017
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_group.group_tip
     *
     * @mbggenerated Sat Mar 18 18:28:12 CST 2017
     */
    private String groupTip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_group.id
     *
     * @return the value of log_group.id
     *
     * @mbggenerated Sat Mar 18 18:28:12 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_group.id
     *
     * @param id the value for log_group.id
     *
     * @mbggenerated Sat Mar 18 18:28:12 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_group.group_name
     *
     * @return the value of log_group.group_name
     *
     * @mbggenerated Sat Mar 18 18:28:12 CST 2017
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_group.group_name
     *
     * @param groupName the value for log_group.group_name
     *
     * @mbggenerated Sat Mar 18 18:28:12 CST 2017
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_group.group_tip
     *
     * @return the value of log_group.group_tip
     *
     * @mbggenerated Sat Mar 18 18:28:12 CST 2017
     */
    public String getGroupTip() {
        return groupTip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_group.group_tip
     *
     * @param groupTip the value for log_group.group_tip
     *
     * @mbggenerated Sat Mar 18 18:28:12 CST 2017
     */
    public void setGroupTip(String groupTip) {
        this.groupTip = groupTip == null ? null : groupTip.trim();
    }
}