package org.companyLog.bean;

public class LogLimitRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_limit_role.id
     *
     * @mbggenerated Sat Mar 18 20:20:25 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_limit_role.log_id
     *
     * @mbggenerated Sat Mar 18 20:20:25 CST 2017
     */
    private String logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_limit_role.role_id
     *
     * @mbggenerated Sat Mar 18 20:20:25 CST 2017
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_limit_role.id
     *
     * @return the value of log_limit_role.id
     *
     * @mbggenerated Sat Mar 18 20:20:25 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_limit_role.id
     *
     * @param id the value for log_limit_role.id
     *
     * @mbggenerated Sat Mar 18 20:20:25 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_limit_role.log_id
     *
     * @return the value of log_limit_role.log_id
     *
     * @mbggenerated Sat Mar 18 20:20:25 CST 2017
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_limit_role.log_id
     *
     * @param logId the value for log_limit_role.log_id
     *
     * @mbggenerated Sat Mar 18 20:20:25 CST 2017
     */
    public void setLogId(String logId) {
        this.logId = logId == null ? null : logId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_limit_role.role_id
     *
     * @return the value of log_limit_role.role_id
     *
     * @mbggenerated Sat Mar 18 20:20:25 CST 2017
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_limit_role.role_id
     *
     * @param roleId the value for log_limit_role.role_id
     *
     * @mbggenerated Sat Mar 18 20:20:25 CST 2017
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}