package org.companyLog.bean;

public class Permission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.id
     *
     * @mbggenerated Thu Mar 16 20:52:44 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_name
     *
     * @mbggenerated Thu Mar 16 20:52:44 CST 2017
     */
    private String permissionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.permission_code
     *
     * @mbggenerated Thu Mar 16 20:52:44 CST 2017
     */
    private String permissionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.url
     *
     * @mbggenerated Thu Mar 16 20:52:44 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column permission.is_default
     *
     * @mbggenerated Thu Mar 16 20:52:44 CST 2017
     */
    private Integer isDefault;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.id
     *
     * @return the value of permission.id
     *
     * @mbggenerated Thu Mar 16 20:52:44 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.id
     *
     * @param id the value for permission.id
     *
     * @mbggenerated Thu Mar 16 20:52:44 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_name
     *
     * @return the value of permission.permission_name
     *
     * @mbggenerated Thu Mar 16 20:52:44 CST 2017
     */
    public String getPermissionName() {
        return permissionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_name
     *
     * @param permissionName the value for permission.permission_name
     *
     * @mbggenerated Thu Mar 16 20:52:44 CST 2017
     */
    public void setPermissionName(String permissionName) {
        this.permissionName = permissionName == null ? null : permissionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.permission_code
     *
     * @return the value of permission.permission_code
     *
     * @mbggenerated Thu Mar 16 20:52:44 CST 2017
     */
    public String getPermissionCode() {
        return permissionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.permission_code
     *
     * @param permissionCode the value for permission.permission_code
     *
     * @mbggenerated Thu Mar 16 20:52:44 CST 2017
     */
    public void setPermissionCode(String permissionCode) {
        this.permissionCode = permissionCode == null ? null : permissionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.url
     *
     * @return the value of permission.url
     *
     * @mbggenerated Thu Mar 16 20:52:44 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.url
     *
     * @param url the value for permission.url
     *
     * @mbggenerated Thu Mar 16 20:52:44 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column permission.is_default
     *
     * @return the value of permission.is_default
     *
     * @mbggenerated Thu Mar 16 20:52:44 CST 2017
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column permission.is_default
     *
     * @param isDefault the value for permission.is_default
     *
     * @mbggenerated Thu Mar 16 20:52:44 CST 2017
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }
}