package org.companyLog.bean;


public class Report {
	
	//自定义
	private String authorName;
	private String receiverName;
	
	
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.id
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.author_id
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    private String authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.receiver_id
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    private String receiverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.begin_date
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    private String beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.end_date
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    private String endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.work_contet
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    private String workContet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.work_summary
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    private String workSummary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.self_evaluation
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    private String selfEvaluation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.leader_evaluation
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    private String leaderEvaluation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.submit_time
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    private String submitTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.update_time
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column report.state
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.id
     *
     * @return the value of report.id
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.id
     *
     * @param id the value for report.id
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.author_id
     *
     * @return the value of report.author_id
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public String getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.author_id
     *
     * @param authorId the value for report.author_id
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public void setAuthorId(String authorId) {
        this.authorId = authorId == null ? null : authorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.receiver_id
     *
     * @return the value of report.receiver_id
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public String getReceiverId() {
        return receiverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.receiver_id
     *
     * @param receiverId the value for report.receiver_id
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public void setReceiverId(String receiverId) {
        this.receiverId = receiverId == null ? null : receiverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.begin_date
     *
     * @return the value of report.begin_date
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public String getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.begin_date
     *
     * @param beginDate the value for report.begin_date
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public void setBeginDate(String beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.end_date
     *
     * @return the value of report.end_date
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.end_date
     *
     * @param endDate the value for report.end_date
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.work_contet
     *
     * @return the value of report.work_contet
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public String getWorkContet() {
        return workContet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.work_contet
     *
     * @param workContet the value for report.work_contet
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public void setWorkContet(String workContet) {
        this.workContet = workContet == null ? null : workContet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.work_summary
     *
     * @return the value of report.work_summary
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public String getWorkSummary() {
        return workSummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.work_summary
     *
     * @param workSummary the value for report.work_summary
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public void setWorkSummary(String workSummary) {
        this.workSummary = workSummary == null ? null : workSummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.self_evaluation
     *
     * @return the value of report.self_evaluation
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public String getSelfEvaluation() {
        return selfEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.self_evaluation
     *
     * @param selfEvaluation the value for report.self_evaluation
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public void setSelfEvaluation(String selfEvaluation) {
        this.selfEvaluation = selfEvaluation == null ? null : selfEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.leader_evaluation
     *
     * @return the value of report.leader_evaluation
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public String getLeaderEvaluation() {
        return leaderEvaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.leader_evaluation
     *
     * @param leaderEvaluation the value for report.leader_evaluation
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public void setLeaderEvaluation(String leaderEvaluation) {
        this.leaderEvaluation = leaderEvaluation == null ? null : leaderEvaluation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.submit_time
     *
     * @return the value of report.submit_time
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public String getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.submit_time
     *
     * @param submitTime the value for report.submit_time
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public void setSubmitTime(String submitTime) {
        this.submitTime = submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.update_time
     *
     * @return the value of report.update_time
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.update_time
     *
     * @param updateTime the value for report.update_time
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column report.state
     *
     * @return the value of report.state
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column report.state
     *
     * @param state the value for report.state
     *
     * @mbggenerated Wed Mar 15 22:23:04 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

	public String getAuthorName() {
		return authorName;
	}

	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	public String getReceiverName() {
		return receiverName;
	}

	public void setReceiverName(String receiverName) {
		this.receiverName = receiverName;
	}
}