package org.companyLog.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.companyLog.bean.LogGroup;

public interface LogGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_group
     *
     * @mbggenerated Sat Mar 18 18:28:12 CST 2017
     */
    @Delete({
        "delete from log_group",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_group
     *
     * @mbggenerated Sat Mar 18 18:28:12 CST 2017
     */
    @Insert({
        "insert into log_group (id, group_name, ",
        "group_tip)",
        "values (#{id,jdbcType=VARCHAR}, #{groupName,jdbcType=VARCHAR}, ",
        "#{groupTip,jdbcType=VARCHAR})"
    })
    int insert(LogGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_group
     *
     * @mbggenerated Sat Mar 18 18:28:12 CST 2017
     */
    @Select({
        "select",
        "id, group_name, group_tip",
        "from log_group",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="group_name", property="groupName", jdbcType=JdbcType.VARCHAR),
        @Result(column="group_tip", property="groupTip", jdbcType=JdbcType.VARCHAR)
    })
    LogGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_group
     *
     * @mbggenerated Sat Mar 18 18:28:12 CST 2017
     */
    @Select({
        "select",
        "id, group_name, group_tip",
        "from log_group"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="group_name", property="groupName", jdbcType=JdbcType.VARCHAR),
        @Result(column="group_tip", property="groupTip", jdbcType=JdbcType.VARCHAR)
    })
    List<LogGroup> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_group
     *
     * @mbggenerated Sat Mar 18 18:28:12 CST 2017
     */
    @Update({
        "update log_group",
        "set group_name = #{groupName,jdbcType=VARCHAR},",
          "group_tip = #{groupTip,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(LogGroup record);
}