package org.companyLog.dao;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.companyLog.bean.RolePermission;

public interface RolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Sun Mar 12 00:03:26 CST 2017
     */
    @Delete({
        "delete from role_permission",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Sun Mar 12 00:03:26 CST 2017
     */
    @Insert({
        "insert into role_permission (id, role_id, ",
        "permission_id)",
        "values (#{id,jdbcType=VARCHAR}, #{roleId,jdbcType=VARCHAR}, ",
        "#{permissionId,jdbcType=VARCHAR})"
    })
    int insert(RolePermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Sun Mar 12 00:03:26 CST 2017
     */
    @Select({
        "select",
        "id, role_id, permission_id",
        "from role_permission",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="role_id", property="roleId", jdbcType=JdbcType.VARCHAR),
        @Result(column="permission_id", property="permissionId", jdbcType=JdbcType.VARCHAR)
    })
    RolePermission selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Sun Mar 12 00:03:26 CST 2017
     */
    @Select({
        "select",
        "id, role_id, permission_id",
        "from role_permission"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="role_id", property="roleId", jdbcType=JdbcType.VARCHAR),
        @Result(column="permission_id", property="permissionId", jdbcType=JdbcType.VARCHAR)
    })
    List<RolePermission> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_permission
     *
     * @mbggenerated Sun Mar 12 00:03:26 CST 2017
     */
    @Update({
        "update role_permission",
        "set role_id = #{roleId,jdbcType=VARCHAR},",
          "permission_id = #{permissionId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(RolePermission record);
    
    
    //自定义
    
    @Delete({
        "delete from role_permission",
        "where role_id = #{0,jdbcType=VARCHAR} ",
        "and permission_id = #{1,jdbcType=VARCHAR}"
    })
    int deleteByRoleIdAndPermissionId(String roleId,String permissionId);
    
    @Delete({
        "delete from role_permission",
        "where role_id = #{roleId,jdbcType=VARCHAR} ",
    })
    int deleteByRoleId(String roleId);
}