package org.companyLog.dao;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.type.JdbcType;
import org.companyLog.bean.Role;
import org.companyLog.bean.UserRole;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun Mar 12 00:03:26 CST 2017
     */
    @Delete({
        "delete from user_role",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun Mar 12 00:03:26 CST 2017
     */
    @Insert({
        "insert into user_role (id, user_id, ",
        "role_id)",
        "values (#{id,jdbcType=VARCHAR}, #{userId,jdbcType=VARCHAR}, ",
        "#{roleId,jdbcType=VARCHAR})"
    })
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun Mar 12 00:03:26 CST 2017
     */
    @Select({
        "select",
        "id, user_id, role_id",
        "from user_role",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_id", property="roleId", jdbcType=JdbcType.VARCHAR)
    })
    UserRole selectByPrimaryKey(String id);
    
//    @Select({
//        "select",
//        "id, user_id, role_id",
//        "from user_role",
//        "where id = #{id,jdbcType=VARCHAR}"
//    })
//    @Results({
//        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
//        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
//        @Result(column="role_id", property="roleId", jdbcType=JdbcType.VARCHAR)
//    })
//    Role selectRoleByUserId(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun Mar 12 00:03:26 CST 2017
     */
    @Select({
        "select",
        "id, user_id, role_id",
        "from user_role"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.VARCHAR),
        @Result(column="role_id", property="roleId", jdbcType=JdbcType.VARCHAR)
    })
    List<UserRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_role
     *
     * @mbggenerated Sun Mar 12 00:03:26 CST 2017
     */
    @Update({
        "update user_role",
        "set user_id = #{userId,jdbcType=VARCHAR},",
          "role_id = #{roleId,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(UserRole record);
    
    
   //自定义
    
    @Delete({
        "delete from user_role",
        "where user_id = #{0,jdbcType=VARCHAR} ",
        "and role_id = #{1,jdbcType=VARCHAR}"
    })
    int deleteByUserIdAndRoleId(String userId,String roleId);
    
    @Delete({
        "delete from user_role",
        "where user_id = #{userId,jdbcType=VARCHAR} ",
    })
    int deleteByUserId(String userId);
    
    @Delete({
        "delete from user_role",
        "where role_id = #{roleId,jdbcType=VARCHAR} ",
    })
    int deleteByRoleId(String roleId);
}